# CLAIRVOYANT ROBO INVESTMENTS: ANY MORE HUMAN AND WE'D BLEED

## Import Libraries

In [34]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import FundamentalAnalysis as fa
import json 
import pandas as pd
from pathlib import Path
import numpy as np
import yaml
import io

## Client Onboarding and Portfolio Selection

In [35]:
## Import client KYC form as .yaml file
with open("kyc_form.yaml") as file:    
    kyc_data = yaml.load(file, Loader=yaml.FullLoader)
    print(kyc_data)

{'intake_form': {'first_name': 'Justin', 'last_name': 'Gouin', 'birth_date': datetime.date(1987, 11, 7), 'annual_income': 100000, 'initial_investment': 20000, 'occupation': None, 'investment_goals': 'growth', 'investment_time_horizon': 30, 'risk_tolerance': 'high', 'investment_constraints': 'none'}}

In [36]:
## View KYC form if desired:
kyc_form = yaml.dump(kyc_data, sort_keys=False)
print(kyc_form)

intake_form:
  first_name: Justin
  last_name: Gouin
  birth_date: 1987-11-07
  annual_income: 100000
  initial_investment: 20000
  occupation: null
  investment_goals: growth
  investment_time_horizon: 30
  risk_tolerance: high
  investment_constraints: none

In [37]:
## Extract key data points from client KYC form
risk = kyc_data["intake_form"]["risk_tolerance"]
income = kyc_data["intake_form"]["annual_income"]
goals = kyc_data["intake_form"]["investment_goals"]
horizon = kyc_data["intake_form"]["investment_time_horizon"]
initial_investment: kyc_data["intake_form"]["initial_investment"]

In [38]:
## Categorize client's Risk Tolerance
if risk == "low":
    r = 0
elif risk == "medium":
    r = 1
elif risk == "high":
    r = 2
print(r)

2

In [39]:
## Categorize client's Annual Income
if income <= 75000:
    i = 0
elif income >= 75001 and income <= 150000:
    i = 1
elif income >= 150001:
    i = 2
print(i)

1

In [40]:
## Categorize client's Investment Goals
if goals == "preservation":
    g = 0
elif goals == "income":
    g = 1
elif goals == "growth":
    g = 2
print(g)

2

In [41]:
### Categorize client's Time Horizon:
if horizon >= 0 and horizon <= 10:
    h = 3
elif horizon >= 11 and horizon <= 20:
    h = 2
elif horizon >= 21:
    h = 1
print(h)

1

In [42]:
## Compile client categorizations to determine portfolio suitability:
client_portfolio_number = r + i + g + h
if client_portfolio_number >= 0 and client_portfolio_number <= 1.5:
    pn = 1
if client_portfolio_number >= 2 and client_portfolio_number <= 4.5:
    pn = 2
if client_portfolio_number >= 5: 
    pn = 3
print(pn)

3

## Define the Portfolios / Import Dataset / Clean Data / Prepare Data for Presentation to Client

#### PORTFOLIO I: GROWING WITH THE MARKET

In [43]:
### EXTRA ## Create a 'for loop' to automatically call APIs based on the Portfolio Number (PN)

In [44]:
## Import Stock Data
stocks = yf.download("SPY AAPL MMM JPM DIS XOM UNH QCOM AMZN GE PYPL MSTR NFlX GBTC ARKK DAL COF CTSH ^TNX", start="2001-04-01", end="2021-04-01").Close
stocks.tail()

[*********************100%***********************]  19 of 19 completed

,AAPL,AMZN,ARKK,COF,CTSH,DAL,DIS,GBTC,GE,JPM,MMM,MSTR,NFLX,PYPL,QCOM,SPY,UNH,XOM,^TNX
Date,,,,,,,,,,,,,,,,,,,
2021-03-26,121.209999,3052.030029,113.970001,129.589996,79.239998,47.660000,185.919998,46.430000,12.99,155.089996,194.880005,624.000000,508.049988,241.029999,132.990005,395.980011,376.480011,57.709999,1.660
2021-03-29,121.389999,3075.729980,111.169998,126.489998,78.059998,47.320000,184.850006,49.450001,12.95,152.679993,195.740005,631.340027,513.950012,235.669998,131.270004,395.779999,379.059998,57.400002,1.721
2021-03-30,119.900002,3055.290039,114.419998,128.559998,78.570000,48.900002,185.529999,50.820000,13.30,154.479996,194.639999,653.979980,513.390015,236.539993,130.110001,394.730011,373.559998,56.689999,1.726
2021-03-31,122.150002,3094.080078,119.949997,127.230003,78.120003,48.279999,184.520004,50.040001,13.13,152.229996,192.679993,678.799988,521.659973,242.839996,132.589996,396.329987,372.070007,55.830002,1.746
2021-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.679

In [45]:
## Analyze the dataset to ensure there are no null entries
stocks.isnull().sum()

AAPL       1
AMZN       1
ARKK    3418
COF        1
CTSH       1
DAL     1529
DIS        1
GBTC    3548
GE         1
JPM        1
MMM        1
MSTR       1
NFLX     285
PYPL    3586
QCOM       1
SPY        1
UNH        1
XOM        1
^TNX      40
dtype: int64

In [46]:
stocks.dropna(inplace=True)
stocks.isnull().sum()

AAPL    0
AMZN    0
ARKK    0
COF     0
CTSH    0
DAL     0
DIS     0
GBTC    0
GE      0
JPM     0
MMM     0
MSTR    0
NFLX    0
PYPL    0
QCOM    0
SPY     0
UNH     0
XOM     0
^TNX    0
dtype: int64

In [47]:
## Create a loop to call a particular PORTFOLIO CONFIGURATION

#### Define Portfolios and Define Code for Selection

In [48]:
portfolio_1 = stocks.drop(columns=["GBTC", "^TNX", "MSTR", "NFLX", "DAL", "^TNX"]) 
portfolio_2 = stocks.drop(columns=["SPY", "MMM", "DIS", "GBTC", "MSTR", "^TNX"])
portfolio_3 = stocks.drop(columns=["SPY", "MMM", "DIS", "UNH", "XOM", "^TNX"])

In [55]:
if pn == 1:
    portfolio = portfolio_1
elif pn == 2:
    portfolio = portfolio_2
elif pn == 3:
    portfolio = portfolio_3

In [56]:
## Calculate the daily returns for the S&P 500
portfolio_rtn = portfolio.pct_change()
portfolio.tail()

,AAPL,AMZN,ARKK,COF,CTSH,DAL,GBTC,GE,JPM,MSTR,NFLX,PYPL,QCOM
Date,,,,,,,,,,,,,
2021-03-25,120.589996,3046.260010,114.419998,127.870003,77.099998,47.009998,44.500000,12.85,152.550003,620.909973,502.859985,234.240005,127.279999
2021-03-26,121.209999,3052.030029,113.970001,129.589996,79.239998,47.660000,46.430000,12.99,155.089996,624.000000,508.049988,241.029999,132.990005
2021-03-29,121.389999,3075.729980,111.169998,126.489998,78.059998,47.320000,49.450001,12.95,152.679993,631.340027,513.950012,235.669998,131.270004
2021-03-30,119.900002,3055.290039,114.419998,128.559998,78.570000,48.900002,50.820000,13.30,154.479996,653.979980,513.390015,236.539993,130.110001
2021-03-31,122.150002,3094.080078,119.949997,127.230003,78.120003,48.279999,50.040001,13.13,152.229996,678.799988,521.659973,242.839996,132.589996

In [57]:
## Calculate the standard deviation
portfolio_std = portfolio_rtn.std()
portfolio_std = portfolio_std.sort_values()
portfolio_std

JPM     0.018880
CTSH    0.018984
AAPL    0.019103
AMZN    0.019181
ARKK    0.020199
PYPL    0.022048
QCOM    0.023363
COF     0.024239
GE      0.024523
DAL     0.026538
NFLX    0.026748
MSTR    0.030421
GBTC    0.060019
dtype: float64

In [58]:
## Calculate the annualized standard deviation
ann_portfolio_std = portfolio_std * np.sqrt(252)
ann_portfolio_std = ann_portfolio_std.sort_values()
ann_portfolio_std

JPM     0.299704
CTSH    0.301356
AAPL    0.303256
AMZN    0.304492
ARKK    0.320651
PYPL    0.350004
QCOM    0.370881
COF     0.384782
GE      0.389290
DAL     0.421270
NFLX    0.424611
MSTR    0.482924
GBTC    0.952773
dtype: float64

In [53]:
fa.available_companies("bee73dfea0cf26c6dca8b1374f4488a5")

,exchange,name,price
symbol,,,
SPY,New York Stock Exchange Arca,SPDR S&P 500,406.360
CMCSA,Nasdaq Global Select,Comcast Corp,54.800
KMI,New York Stock Exchange,Kinder Morgan Inc,16.660
INTC,Nasdaq Global Select,Intel Corp,66.540
MU,Nasdaq Global Select,Micron Technology Inc,93.750
GDX,New York Stock Exchange Arca,VanEck Vectors Gold Miners,33.710
GE,New York Stock Exchange,General Electric Co,13.460
BAC,New York Stock Exchange,Bank of America Corp,39.800
EEM,New York Stock Exchange Arca,iShares MSCI Emerging Index Fund,54.070
XLF,New York Stock Exchange Arca,SPDR Select Sector Fund - Financial,34.740
AAPL,Nasdaq Global Select,Apple Inc,125.900
MSFT,Nasdaq Global Select,Microsoft Corp,249.070
SIRI,Nasdaq Global Select,Sirius XM Holdings Inc,6.300
HPQ,New York Stock Exchange,HP Inc,32.460
CX,New York Stock Exchange,Cemex S.A.B. de C.V. Sponsored ADR,7.170
EFA,New York Stock Exchange Arca,iShares MSCI EAFE,77.980
CZR,Nasdaq Global Select,Caesars Entertainment Inc,90.180
QQQ,Nasdaq Global Market,PowerShares QQQ Trust Series 1,331.050
F,New York Stock Exchange,Ford Motor Co,12.700
AMD,Nasdaq Capital Market,Advanced Micro Devices Inc,81.430
SNAP,New York Stock Exchange,Snap Inc,54.110
FB,Nasdaq Global Select,Facebook Inc,308.910
WFC,New York Stock Exchange,Wells Fargo & Co,39.480
AIG,New York Stock Exchange,American International Group Inc,46.750
T,New York Stock Exchange,AT&T Inc,30.710
C,New York Stock Exchange,Citigroup Inc,72.750
VALE,New York Stock Exchange,VALE S.A. American Depositary Shares Each Repr...,18.280
MS,New York Stock Exchange,Morgan Stanley,78.000
AKS,New York Stock Exchange,AK Steel Holding Corporation,1.550
JPM,New York Stock Exchange,JPMorgan Chase & Co,153.620
...,...,...,...
AACOU,Nasdaq,Advancit Acquisition Corp. I,0.000
CNAQU,Nasdaq,Chardan NexTech Acquisition Corp. Unit,0.000
RMGDU,Nasdaq,RMG Acquisition Corp. IV,0.000
COUR,New York Stock Exchange,"Coursera, Inc.",49.610
PGD.AX,ASX,Peregrine Gold Ltd,0.295
ACHL,NasdaqGS,Achilles Therapeutics plc American Depositary ...,14.920
ROO.L,LSE,Deliveroo Holdings Plc,282.000
MBTCU,Nasdaq Capital Market,Nocturne Acquisition Corporation,10.080
543282.BO,BSE,Niks Technology Limited,0.000
EVOJW,Nasdaq,Evo Acquisition Corp. Warrant,0.000
KVSD,Nasdaq,Khosla Ventures Acquisition Co. IV,0.000
KLTR,Nasdaq,KALTURA INC,0.000
ENNVW,Nasdaq,ECP Environmental Growth Opportunities Corp.,0.000
EVOJ,Nasdaq,Evo Acquisition Corp. Class A Common Stock,0.000
ULCC,NasdaqGS,"Frontier Group Holdings, Inc. Common Stock",19.130
COMP,New York Stock Exchange,"Compass, Inc.",18.590
ENNV,Nasdaq,ECP Environmental Growth Opportunities Corp.,0.000
UTME,Nasdaq,UTime Ltd,0.000
GIGGW,NasdaqGS,"GigCapital4, Inc. Warrant",0.970
KARO,NasdaqGS,Karooooo Ltd. Ordinary Shares,33.700
QWNBU,Nasdaq,Queen's Gambit Growth Capital II,0.000
ACBAU,Nasdaq,Ace Global Business Acquisition Limited Unit,0.000
IINN,Nasdaq,Inspira Technologies OXY B.H.N. Ltd,0.000
EM,NasdaqGS,Smart Share Global Limited American Depositary...,8.050
EKOP.BR,Brussels,Ekopak NV,16.100
QPM.AX,ASX,Queensland Pacific Metals Limited,0.091
LGACW,Nasdaq,Lazard Growth Acquisition Corp. I Warrants,0.000
SCOB,Nasdaq,ScION Tech Growth II Class A Ordinary Shares,11.050
SCOBW,Nasdaq,ScION Tech Growth II Warrants,0.000
LGAC,Nasdaq,Lazard Growth Acquisition Corp. I Ordinary Shares,11.050

In [68]:
import FundamentalAnalysis as fa

ticker = "AAPL"
api_key = "bee73dfea0cf26c6dca8b1374f4488a5"

# Show the available companies
companies = fa.available_companies(api_key)

# Collect general company information
profile = fa.profile(ticker, api_key)

# Collect recent company quotes
quotes = fa.quote(ticker, api_key)

# Collect market cap and enterprise value
entreprise_value = fa.enterprise(ticker, api_key)

# Show recommendations of Analysts
ratings = fa.rating(ticker, api_key)

# Obtain DCFs over time
dcf_annually = fa.discounted_cash_flow(ticker, api_key, period="annual")
dcf_quarterly = fa.discounted_cash_flow(ticker, api_key, period="quarter")

# Collect the Balance Sheet statements
balance_sheet_annually = fa.balance_sheet_statement(ticker, api_key, period="annual")
balance_sheet_quarterly = fa.balance_sheet_statement(ticker, api_key, period="quarter")

# Collect the Income Statements
income_statement_annually = fa.income_statement(ticker, api_key, period="annual")
income_statement_quarterly = fa.income_statement(ticker, api_key, period="quarter")

# Collect the Cash Flow Statements
cash_flow_statement_annually = fa.cash_flow_statement(ticker, api_key, period="annual")
cash_flow_statement_quarterly = fa.cash_flow_statement(ticker, api_key, period="quarter")

# Show Key Metrics
key_metrics_annually = fa.key_metrics(ticker, api_key, period="annual")
key_metrics_quarterly = fa.key_metrics(ticker, api_key, period="quarter")

# Show a large set of in-depth ratios
financial_ratios_annually = fa.financial_ratios(ticker, api_key, period="annual")
financial_ratios_quarterly = fa.financial_ratios(ticker, api_key, period="quarter")

# Show the growth of the company
growth_annually = fa.financial_statement_growth(ticker, api_key, period="annual")
growth_quarterly = fa.financial_statement_growth(ticker, api_key, period="quarter")

# Download general stock data
stock_data = fa.stock_data(ticker, period="ytd", interval="1d")

# Download detailed stock data
stock_data_detailed = fa.stock_data_detailed(ticker, api_key, begin="2000-01-01", end="2020-01-01")

In [69]:
SPY_profile = fa.financial_ratios("ICBU", api_key)
display(SPY_profile)

Empty DataFrame
Columns: []
Index: []

In [70]:
data = requests.get(request_url).json()

NameError: name 'requests' is not defined